Areas/Admin/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Asm.Models.Entity;

namespace Asm.Areas.Admin.Controllers
{
    public class AccountsController : Controller
    {
        private Manage_Context db = new Manage_Context();

        public ActionResult Welcome()
        {
            return View();
        }
        // GET: Admin/Accounts
        public ActionResult Index()
        {
            var accounts = db.Accounts.Include(a => a.Role1);
            return View(accounts.ToList());
        }

        // GET: Admin/Accounts/Details/5

        // GET: Admin/Accounts/Create
        [HttpPost]
        public ActionResult Search(string searchKey)
        {
            var a = db.Accounts.Where(t => t.Name.Contains(searchKey) || searchKey == null).ToList();
            return View(a);
        }

        [HttpPost]
        public ActionResult SearchRole(string role)
        {
            var a = db.Accounts.Where(t => t.Role.Contains(role) || role == null).ToList();
            return View(a);
        }
        public ActionResult Create()
        {
            ViewBag.Role = new SelectList(db.Roles, "RoleName", "RoleName");
            return View();
        }

        // POST: Admin/Accounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AccID,Name,Email,Password,Role,DoB,PhoneNo,ToeicScore")] Account account)
        {
            if (ModelState.IsValid)
            {
                db.Accounts.Add(account);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Role = new SelectList(db.Roles, "RoleName", "RoleName", account.Role);
            return View(account);
        }

        // GET: Admin/Accounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            ViewBag.Role = new SelectList(db.Roles, "RoleName", "RoleName", account.Role);
            return View(account);
        }

        // POST: Admin/Accounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AccID,Name,Email,Password,Role,DoB,PhoneNo,ToeicScore")] Account account)
        {
            if (ModelState.IsValid)
            {
                db.Entry(account).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Role = new SelectList(db.Roles, "RoleName", "RoleName", account.Role);
            return View(account);
        }

        // GET: Admin/Accounts/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            var model = db.Accounts.Where(x => x.AccID == id).FirstOrDefault();
            var model1 = db.Courses.Where(x => x.TrainerID == id).FirstOrDefault();
            model1.TrainerID = null;
            if (model != null)
            {
                db.Accounts.Remove(model);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return new HttpNotFoundResult();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Staff/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Asm.Models.Entity;

namespace Asm.Areas.Staff.Controllers
{
    public class CoursesController : Controller
    {
        private Manages_Context db = new Manages_Context();
        //private Model1 db = new Model1();

        // GET: Staff/Courses
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.Account).Include(c => c.CourseCategory);
            return View(courses.ToList());
        }

        [HttpPost]
        public ActionResult Search(string searchKey)
        {
            var a = db.Courses.Where(t => t.CourseName.Contains(searchKey) || searchKey == null).ToList();
            return View(a);
        }

        // GET: Staff/Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Staff/Courses/Create
        public ActionResult Create()
        {
            ViewBag.TrainerID = new SelectList(db.Accounts, "AccID", "Name");
            ViewBag.CatID = new SelectList(db.CourseCategories, "CourseCatID", "Name");
            return View();
        }

        // POST: Staff/Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,CatID,CourseName,Description,TrainerID")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TrainerID = new SelectList(db.Accounts, "AccID", "Name", course.TrainerID);
            ViewBag.CatID = new SelectList(db.CourseCategories, "CourseCatID", "Name", course.CatID);
            return View(course);
        }

        // GET: Staff/Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.TrainerID = new SelectList(db.Accounts, "AccID", "Name", course.TrainerID);
            ViewBag.CatID = new SelectList(db.CourseCategories, "CourseCatID", "Name", course.CatID);
            return View(course);
        }

        // POST: Staff/Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseID,CatID,CourseName,Description,TrainerID")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TrainerID = new SelectList(db.Accounts, "AccID", "Name", course.TrainerID);
            ViewBag.CatID = new SelectList(db.CourseCategories, "CourseCatID", "Name", course.CatID);
            return View(course);
        }

        public ActionResult Assigned(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            var findTrainer = db.Accounts.Where(f => f.Role.Equals("Trainer"));
            ViewBag.TrainerID = new SelectList(findTrainer, "AccID", "Name");
            ViewBag.CatID = new SelectList(db.CourseCategories, "CourseCatID", "Name", course.CatID);
            return View(course);
        }

        // POST: Staff/Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Assigned([Bind(Include = "CourseID,CatID,CourseName,Description,TrainerID")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TrainerID = new SelectList(db.Accounts, "AccID", "Name", course.TrainerID);
            ViewBag.CatID = new SelectList(db.CourseCategories, "CourseCatID", "Name", course.CatID);
            return View(course);
        }

        // GET: Staff/Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            var model = db.Courses.Where(x => x.CourseID == id).FirstOrDefault();
            var model1 = db.Assigned_Course.Where(x => x.CourseID == id).FirstOrDefault();
            if (model != null)
            {
                db.Courses.Remove(model);
                if(model1 != null)
                {
                    db.Assigned_Course.Remove(model1);
                }
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return new HttpNotFoundResult();
        }

        // POST: Staff/Courses/Delete/5

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Trainer/Views/Shared/Header.cshtml
<div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
    <!--left-fixed -navigation-->
    <aside class="sidebar-left">
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1><a class="navbar-brand" href="index.html"><img src="https://www.fpt.com.vn/Content/home/images/icon/ic-logo.png" alt="" style="height: 50px"></a></h1>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="">
                        <a href="@Url.Action("Index", "Accounts")">
                            <i class="fa fa-table"></i>
                            <span>View Profile</span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href="@Url.Action("Index", "Courses")">
                            <i class="fa fa-edit"></i>
                            <span>View Asigned Course</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
    </aside>
</div>
<!--left-fixed -navigation-->
<!-- header-starts -->
<div class="sticky-header header-section ">
    <div class="header-left">
        <div class="clearfix"> </div>
    </div>
    <div class="header-right">
        <div class="profile_details">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <div class="user-name">
                                <p>Welcome Trainer</p>
                            </div>
                            <i class="fa fa-angle-down lnr"></i>
                            <i class="fa fa-angle-up lnr"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="@Url.Action("Logout", "Home", new { area = "" })"><i class="fa fa-sign-out"></i> Logout</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
    <div class="clearfix"> </div>
</div>

Areas/Trainer/Views/Shared/_MyLayout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <title>Training Activity Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    @Styles.Render("~/Content/cssfile")
    @Scripts.Render("~/bundles/bootstrapfile")
    <script type="text/javascript" src="https://kit.fontawesome.com/a076d05399.js"></script>

</head>
<body class="cbp-spmenu-push">
    <div class="main-content">
        @Html.Partial("Header")

        <!-- //header-ends -->
        <!-- main content start-->
        <div id="page-wrapper">
            <div class="main-page">
                <div class="charts">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!--footer-->

        <div class="footer">
            <p>&copy; Copyright @@2021</p>
        </div>

        <!--//footer-->
    </div>


</body>
</html>