Models/Entity/Assigned_Course.cs
namespace Asm.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Assigned_Course
    {
        public int id { get; set; }

        public int CourseID { get; set; }

        public int TraineeID { get; set; }

        public virtual Account Account { get; set; }

        public virtual Course Course { get; set; }
    }
}

Areas/Trainee/Controllers/Assigned_CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Asm.Models.Entity;

namespace Asm.Areas.Trainee.Controllers
{
    public class Assigned_CourseController : Controller
    {
        private Manages_Context db = new Manages_Context();

        // GET: Trainee/Assigned_Course
        public ActionResult Index()
        {
            int sessionID = Convert.ToInt32(Session["AccountID"].ToString());
            var assigned_Course = db.Assigned_Course.Include(a => a.Account).Include(a => a.Course).Where(a => a.TraineeID == sessionID);

            Course trainerName = db.Courses.Include(c => c.Account).Where(x => x.CourseID == sessionID).First();
            ViewBag.name = trainerName.Account.Name;
            return View(assigned_Course.ToList());
        }

        // GET: Trainee/Assigned_Course/Details/5
        public ActionResult Details(int? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            Course courseName = db.Courses.Find(id);
            ViewBag.courseName = courseName.CourseName;
            Course courseCategory = db.Courses.Include(c => c.CourseCategory).Where(x => x.CourseID == id).First();
            ViewBag.courseCategory = courseName.CourseCategory.Name;
            Course trainerName = db.Courses.Include(c => c.Account).Where(x => x.CourseID == id).First();
            ViewBag.name = trainerName.Account.Name;
            //if (course == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(course);

            List<Assigned_Course> courses = db.Assigned_Course.Include(c => c.Account).Include(c => c.Course).Where(x => x.CourseID == id).ToList();
            return View(courses);
        }

        // GET: Trainee/Assigned_Course/Create

        public ActionResult IndexCourse()
        {
            //var courses = db.Courses.Include(c => c.Account).Include(c => c.CourseCategory);
            var course = db.Courses.Include(a => a.Account);
            return View(course.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Trainee/Views/Assigned_Course/Details.cshtml
@model IEnumerable<Asm.Models.Entity.Assigned_Course>

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Trainee/Views/Shared/_MyLayout.cshtml";
}

<h2> </h2>

<div class="bs-example widget-shadow" data-example-id="hoverable-table">
    <br />
    <h3 style="margin-left:20px;"> @ViewBag.courseName</h3>
    <p style="margin-left:20px; color:gray">Category: @ViewBag.courseCategory</p>
    <p style="margin-left:20px; color:gray">Trainer: @ViewBag.name</p>
    <hr />
    <table class="table " style="width:95%; margin-left:20px; padding-bottom:10px">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Account.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Account.Email)</th>
                <th>@Html.DisplayNameFor(model => model.Account.PhoneNo)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="active">
                    <td style="background-color:white">@Html.DisplayFor(modelItem => item.Account.Name)</td>
                    <td style="background-color:white">@Html.DisplayFor(modelItem => item.Account.Email)</td>
                    <td style="background-color:white">@Html.DisplayFor(modelItem => item.Account.PhoneNo)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Areas/Trainee/Views/Assigned_Course/Index.cshtml
@model IEnumerable<Asm.Models.Entity.Assigned_Course>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Trainee/Views/Shared/_MyLayout.cshtml";
}

<h2>Asigned Course</h2>

<br />
<br />

<ul style="list-style:none;display:inline-block;">
    @foreach (var item in Model)
    {
        <li style="display:inline-block; margin-right:80px;">
            <div class="card" style=" border-color:lightgray; border-style: solid; border-width:1px; width:345px; ">
                <img class="card-img-top" src="https://www.fpt.com.vn/Content/home/images/img/fptf4.jpg" style="height:200px">
                <div class="card-body" style="text-align:center; margin-top:20px">
                    <h4 class="card-title" style="font-weight:bold; ">@Html.DisplayFor(modelItem => item.Course.CourseName)</h4>
                    <p class="card-text" style="margin-top:20px; margin-bottom:10px">Trainer: @ViewBag.Name</p>
                </div>
                <button type="button" class="btn btn-primary" style="margin-left:100px"><a href="@Url.Action("Details", "Assigned_Course", new { id = item.CourseID })" style="color:white">View Details</a></button>
                <br />
                <br />
            </div>
        </li>
    }
</ul>

Areas/Trainee/Views/Assigned_Course/IndexCourse.cshtml
@model IEnumerable<Asm.Models.Entity.Course>

@{
    ViewBag.Title = "IndexCourse";
    Layout = "~/Areas/Trainee/Views/Shared/_MyLayout.cshtml";
}
<h2>Available Course</h2>
<br />

<ul style="list-style:none;display:inline-block;">
    @foreach (var item in Model)
    {
        <li style="display:inline-block; margin-right:100px;margin-bottom:20px">
            <div class="card" style=" border-color:lightgray; border-style: solid; border-width:1px; width:345px; ">
                <img class="card-img-top" src="https://www.fpt.com.vn/Content/home/images/img/fptf4.jpg" style="height:200px">
                <div class="card-body" style="text-align:center; margin-top:20px">
                    <h4 class="card-title" style="font-weight:bold; ">@Html.DisplayFor(modelItem => item.CourseName)</h4>
                    <p class="card-text" style="margin-top:20px; margin-bottom:10px">Trainer: @Html.DisplayFor(modelItem => item.Account.Name)</p>
                </div>
                <br />
            </div>
        </li>
    }
</ul>