Models/Entity/CourseCategory.cs
namespace Asm.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("CourseCategory")]
    public partial class CourseCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseCategory()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        public int CourseCatID { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}

Areas/Staff/Controllers/CourseCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Asm.Models.Entity;

namespace Asm.Areas.Staff.Controllers
{
    public class CourseCategoriesController : Controller
    {
        private Manages_Context db = new Manages_Context();

        // GET: Staff/CourseCategories
        public ActionResult Index()
        {
            return View(db.CourseCategories.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Staff/CourseCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseCatID,Name,Description")] CourseCategory courseCategory)
        {
            if (ModelState.IsValid)
            {
                db.CourseCategories.Add(courseCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(courseCategory);
        }

        // GET: Staff/CourseCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseCategory courseCategory = db.CourseCategories.Find(id);
            if (courseCategory == null)
            {
                return HttpNotFound();
            }
            return View(courseCategory);
        }

        // POST: Staff/CourseCategories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseCatID,Name,Description")] CourseCategory courseCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(courseCategory);
        }

        // GET: Staff/CourseCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            var model = db.CourseCategories.Where(x => x.CourseCatID == id).FirstOrDefault();
            var model1 = db.Courses.Where(x => x.CatID == id).FirstOrDefault();
            if (model != null)
            {
                db.CourseCategories.Remove(model);
                if(model1 != null)
                {
                    db.Courses.Remove(model1);
                }
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return new HttpNotFoundResult();
        }

        // POST: Staff/CourseCategories/Delete/5

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Staff/Views/CourseCategories/Create.cshtml
@model Asm.Models.Entity.CourseCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Staff/Views/Shared/_MyLayout.cshtml";
}

<h2> </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class=" form-grids row form-grids-right">
        <div class="widget-shadow " data-example-id="basic-forms">
            <div class="form-title">
                <h4>Add Category</h4>
            </div>
            <div class="form-body form-horizontal">
                <form class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-offset-2">
                        <button type="submit" class="btn btn-warning">SUBMIT</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

Areas/Staff/Views/CourseCategories/Edit.cshtml
@model Asm.Models.Entity.CourseCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Staff/Views/Shared/_MyLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class=" form-grids row form-grids-right">
        <div class="widget-shadow " data-example-id="basic-forms">
            <div class="form-title">
                <h4>Edit category</h4>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CourseCatID)

            <div class="form-body form-horizontal">
                <form class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-offset-2">
                        <button type="submit" class="btn btn-warning">SUBMIT</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

Areas/Staff/Views/CourseCategories/Index.cshtml
@model IEnumerable<Asm.Models.Entity.CourseCategory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Staff/Views/Shared/_MyLayout.cshtml";
}

<h2> </h2>

<div class="bs-example widget-shadow" data-example-id="hoverable-table">
    <br />
    <h3 style="margin-left:20px;"> Category List</h3>
    <br />
    <button class="btn btn-warning" style="margin-left:20px;"><a href="@Url.Action("Create", "CourseCategories")" style="color:white">ADD CATEGORY</a></button>
    <hr />
    <table class="table " style="width:95%; margin-left:20px; padding-bottom:10px">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="active">
                    <td style="background-color:white">@Html.DisplayFor(modelItem => item.Name)</td>
                    <td style="background-color:white">@Html.DisplayFor(modelItem => item.Description)</td>
                    <td style="background-color:white">
                        @Html.ActionLink("Edit", "Edit", new { id = item.CourseCatID }) |
                        <a id="deleteItem" class="deleteItem" data-target="#basic"
                           data-toggle="modal"
                           data-path="@Url.Action("Delete", "CourseCategories", new { id = @item.CourseCatID })" style="cursor:pointer">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Delete Confirmation</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
                <button id="btnContinueDelete" type="button" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</div>

<script>
    var path_to_delete;

    $(".deleteItem").click(function (e) {
        path_to_delete = $(this).data('path');
    });

    $('#btnContinueDelete').click(function () {
        window.location = path_to_delete;
    });
</script>